### ISSUE TITLE
To change options to subcommands

### ISSUE THREAD

**Issue by tdviet** [IISAS/ai4eosc_client#1]
To change options `deployments --create`, `deployments --delete` and so on to subcommands `deployments create`, `deployments delete` for more user-friendly interaction., e.g. auto-completion, different help texts for different subcommands.  For example: change

`$ ai4eosccli deployments --create ...`

to
`$ ai4eosccli deployments create ...`

**Comment by ondrej2** [comment]
Done, subcommands are info, deployment, module
