### ISSUE TITLE
Add support for retrieving access tokens from oidc-agent and mytoken 

### ISSUE THREAD

**Issue by tdviet** [IISAS/ai4eosc_client#2]
Access tokens have short lifetime (1 hour) so for long work, they should be generated/managed by external tools (oidc-agent, mytoken). The CLI should be able to retrieve the token from the tools directly

**Comment by ondrej2** [comment]
oidc-agent and mytoken support copied from fedcloudclient, including option names. Changed the logic to fit our case.
