### ISSUE TITLE
Add github workflows for quality assurance (linting and toxing)

### ISSUE THREAD

**Issue by tdviet** [IISAS/ai4eosc_client#4]
See examples:
Linting: https://github.com/tdviet/fedcloudclient/blob/master/.github/workflows/lint.yml
Toxing: https://github.com/AI4EOSC/ai4-papi/blob/tox/.github/workflows/ci.yml

**Comment by ondrej2** [comment]
Linting added and fixed/tuned to show no error. Pylint so far disabled, will be enabled later.

**Comment by ondrej2** [comment]
added tox tests, all fine, closing issue
